name: hospital_qr_frontend
description: Doctor app for Hospital QR system
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  image_picker: ^0.8.7+5
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
